name: Android CI

on:
  workflow_dispatch: {}
  push:
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug apk
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assembleDebug

      - name: Build release apk
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assembleRelease
        
      - name: Print version name
        run: |
          APK_NAME="LeafIDE-$(./gradlew -q printVersionName)"
          echo $APK_NAME
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV

      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APK_NAME }}-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload release artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APK_NAME }}-release
          path: app/build/outputs/apk/release/app-release.apk
